### ISSUE TITLE
Bug: System gets unresponsive while changes are done in TemplateBuilder - found during field trip (April)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#1164]
When someone is using the system if we go to the Templates page - there is an error display for the other user! We need to have a way to at least display that the system is under maintenance and will be back to live shortly.

**Comment by CarlosNZ** [comment]
I really don't see how this could happen. I'll test it out tomorrow and see if I can replicate it.

**Comment by CarlosNZ** [comment]
I can't replicate this. Cloned Angola setup onto demo server 50008 with latest snapshot. Running as Admin in Firefox, with basic user in Chrome. No problems at all when Admin is using the templates list or the template builder.

Suspect that whatever errors you saw were due to something else entirely. If you can replicate, please describe steps.

Otherwise, can we close this?

**Comment by CarlosNZ** [comment]
Fixed in back-end https://github.com/openmsupply/application-manager-server/pull/736
