### ISSUE TITLE
Password hashing (and salting)

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#149]
Part of [Epic #12](https://github.com/openmsupply/application-manager-web-app/issues/95)

### Back-end:

1.  ~~Add new column to `user` table -- `password_salt`~~ (Don't need -- bcrypt incorporates salt into hash string)
2. ~~Amend "createUser" Action to take `passwordSalt` parameter and write this value to above field~~ (Don't need)
3. ~~Update template with expression to extract `passwordSalt` field from response object for Action~~ (Don't need)
4. Create new endpoint `/createHash`, which takes in password, generates random salt, hashes password+salt (bcrypt), then returns `hash` (Might not need this -- initial hashing can probably be done in front-end password plugin, since salt is generated simultaneously using `bcrypt`)
5. Amend `/login` endpoint to take username & password, and perform hashing using stored salt. (as opposed to calculating hash in browser)

### Front-end:

1. Amend `login` method to not do hashing (send password to server)

### Form Element plugin: (To do in separate issue #253)

Create a new formElement plugin called "passwordCreate", which works as follows:
1. Displays similar to `shortText`, with same parameters, except user input is masked "•••••••"
2. Checkbox next to input field to "Show password" (Changes masked chars to text)
4. Show a second input field for password confirmation.
3. On Input Lose Focus (Application View),
 - Check both password inputs match, set error state if not.
 - If they do: send password to above `/createHash` endpoint, then put returned `hash` into response.text. Ensure actual password is NEVER stored in response or it could be saved to DB.
4. Summary view: Display password response as "•••••••" (it'll have to be arbitrary length, since original password won't be accessible from here)
5. Note that password cannot be reloaded if the form is refreshed, or paged back from Summary, as it's not stored remotely. The user will have to re-enter it, so we need to set the `initialValue` back to "" for password types on page load. (This should fine, as user registration should be filled in and submitted in one go, as they won't have any way to re-access their application form yet -- otherwise we'll have to do a lot more work to keep the password available locally without sending it to the server)

**Note**: seems like varying opinions on whether to do server-side or client-side hashing. However I found this to be the most convincing argument for server-side: https://myers.io/2016/09/08/why-you-shouldnt-hash-on-the-client/

**Comment by CarlosNZ** [comment]
And are there any preferred libraries for hashing, random-string generating, etc.? [bcrypt](https://www.npmjs.com/package/bcrypt)?

**Comment by andreievg** [comment]
> During login, first run GraphQL query to fetch salt string for username

I think it's ok to send raw password over SSL, as long as we dont' log any of the request parameters to console or file on backend. Back end can use salt for user table to do the hashing.

If we want to do hashing/salting during login on front end, we can add an endpoint (GraphQL queries on user table would be pretty restricted). If we do an endpoint to get salt for a user we would have to do some trickery to make sure valid username can't be deduced. (we would need to return random salt for username that doesn't exists, and persist that salt for subsequent queries for salt for that non-existing username)

> Ideally this can work as an extension of "shortText" (using password: true parameter), but it might be necessary to create a dedicated "PasswordField" plugin.

Would prefer a seperate component, with two masked field (password confirmation)

> On Input Lose Focus (Application View):
> Generate random salt (random 8-char alphanumeric string?)

Could do this as initialValue for stateful salt variable, and yeah 8 char alphanumeric should be fine for now.

> Calculate SHA-1 (?) hash of password+salt

Sure, as long as we use the same for back end and front end it should be fine.

> And are there any preferred libraries for hashing, random-string generating, etc.? bcrypt?

It's been awhile since I've done any crypto stuff. And never actually did it on front end. The only criteria, is it need to work on front end (doesn't use C binaries etc..) and be lightweight (dont' want to bloat our bundle)

If there is no option like this, then we would need an endpoint to provide hashedPassword given password and salt (might be a better way actually, keep it all in one place on backend) <- preferred option. 

`bcrypt` seems pretty popular for hashing. And random string generating should be easy enough:

(i couldn't resits)

```
const chars = [];
for(let i = 0;i<8;i++) chars.push(Math.floor(Math.random() * 42) + 48);
console.log(String.fromCharCode(...chars));
```

**Comment by CarlosNZ** [comment]
Okay, have updated original post solution based on comments and discussion.
