### ISSUE TITLE
Collapsibility for application/review sections

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#217]
Should be used in Application Summary and Review pages. 
The current section should sticky to the top, collapsed sections don't stick.

Current design layout:
![Screen Shot 2021-01-06 at 3 17 28 PM](https://user-images.githubusercontent.com/5456533/103721363-56378c80-5032-11eb-8325-06e824f90da6.png)

**Comment by CarlosNZ** [comment]
It's fairly simple to implement the Drop-down accordion, but I'm having trouble with the Sticky functionality.

The problem is, the Sticky requires a "context" attribute, and the [examples in Semantic](https://react.semantic-ui.com/modules/sticky/#usage-above-content) use `createRef` to define refs. But the "ref" attribute doesn't work in functional components (see [here](https://reactjs.org/docs/refs-and-the-dom.html#refs-and-function-components), and I don't really understand how createRef and useRef work enough to figure it out.

Will see what you guys think at next meeting.

**Comment by CarlosNZ** [comment]
As discussed, made new issue for Sticky functionality: #254
