### ISSUE TITLE
Bug: not displaying current user menu items after login - only after refreshing the page

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#284]

**Comment by CarlosNZ** [comment]
I've found the problem here -- the UserState context wasn't setting `isLoading` back to `false` in the case when it didn't run `fetchUserInfo` (i.e. it already had the info from login). Needed to add `dispatch({ type: 'setLoading', isLoading: false })` to the `else` block at the end of `onLogin()`.

I've added this fix to my current branch, so I'll push it out with my next PR if that's okay? Or if you want to quickly push it to master, just add these lines from line 93:

```
else {
      dispatch({ type: 'setCurrentUser', newUser: user, newPermissions: permissions })
      dispatch({ type: 'setLoading', isLoading: false })
    }
```
