### ISSUE TITLE
Bug: Loading the Submission page after application is submitted

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#290]
Not all the times the submission page is loading, this is to do with the order of things. Some times, when trying to load the submission page the application is still not submitted! It's easy to see that by logging on `useSubmitApplication` method: `onCompleted` and when the push to Submission page happens on `ApplicationOverview`. Even though there is a await on the submit process, this is returned before the process of submitting finishes. We need to change to use the onCompleted call back or other mechanism to prevent some failures to load Submission page.

**Comment by CarlosNZ** [comment]
Not sure if this is related, but I just noticed this error go by in the back-end when submitting a User registration.
![Screen Shot 2021-01-22 at 11 47 30 AM](https://user-images.githubusercontent.com/5456533/105424604-80cd4a80-5cac-11eb-9340-7a434da3063f.png)

No idea what the problem is, but might help in tracking down the root of this issue.
