### ISSUE TITLE
Bug: When loading Application/Review after it's created the page 404 is loaded and needs a refresh page to load properly

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#609]

**Comment by CarlosNZ** [comment]
Is this for Applications and Reviews? I'd only noticed on Reviews.

**Comment by andreievg** [comment]
yeah this is one is for application, it's a bit tricky to replicate. Have to clear cache and hard reload, then any new application should show 404

**Comment by andreievg** [comment]
I'll have a go at fixing it now

**Comment by andreievg** [comment]
also need to reinitialise database

**Comment by andreievg** [comment]
for review it looks like 'createReview' mutation requires output in this format (not sure how it was working previously):

```
review {
        id
        reviewAssignment {
          id
          reviews {
            nodes {
              id
            }
          }
        }
      }
```

**Comment by andreievg** [comment]
the error that we sometimes get when creating application, is due to stage increment happening asyncronously (trigger is already set to null), most times this is ok as asynchronous action will happen before trigger is set to null. can be replicated by extending stage increment -> `  await (new Promise(resolve => setTimeout(resolve, 1000)))` at line 12 in `incrementStage.ts`, then try to create any application. Can be fixed by making those actions sequential
