### ISSUE TITLE
Help text in application form sidebar

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#681]
Just putting this here as a discussion location for how we should handle this. 

Deb's design has this "help" text in the right-hand sidebar:
<img width="942" alt="Screen Shot 2021-05-07 at 11 24 05 AM" src="https://user-images.githubusercontent.com/5456533/117377279-048f0800-af27-11eb-926a-9f4b29563ffb.png">

At first I thought we could just add another field to template elements, but that won't be straightfoward since the right-hand column is outside the ApplicationViewWrapper component, so won't have access to plugin values.

Here are some suggestions of how we could handle it:

1. Make the elements column (middle) and the right-hand column just one wider column, with the elements limited by width. Then we could display help tips inline with the element. I think it'll be fine for overflow to hang down into the area of the next element, with a little CSS magic.
2. Keep help text separate from elements completely, and just store them as part of the template.  Each would contain configuration of its text, the section/page to associate with, and a vertical offset.
3. Do away with it completely and find some other use for this extra space. (We can include any relevant "helper" info with the element description field)

What are your thoughts?

Personally I'm leaning towards option 3, but maybe option 1 (don't really care for option 2 the more I think about it). We could see what Deb comes up with as an alternative perhaps? One good thing about option 1 is that we could have an option for a TextInfo plugin to "span" the whole width and not just be limited to the main elements "column".

(Note: I'm also assuming we would hide this content on mobile)

**Comment by andreievg** [comment]
1 - I like this but I think overlap would be an issue ?
2 - Could be per page I guess, in designs it seems to be directed at the form element though
3a - Could do a kind of a help accordion (with help icon as the title), this would be more portable to mobile
3b -Like one and 3a, show help tip, restricted by the height of form element (add ...), when form element in focus, show full help tip (some css trickery still)

Can ask Debs about 3a and 3b or opened ended 3.
I think it's worth asking, since in her reply, she didn't give any guidance of what happens if two consecutive  form elements have the help tip (and it looks like they will overlap since the help tip in the example spans beyond the form element's height) 
Andrei
```
Info/descriptions in application form
We were wondering about the info on the right hand side of form elements, do they appear for currently ‘entered’ elements or all of them ?
```
Debs
```
My thinking on this "Info description" text is to only show on certain inputs where you need to show extra information (paragraph) to help user with extra info. So show all the time, not just on entered elements. Not to be used on every element though.
```

**Comment by CarlosNZ** [comment]
Cool, will implement as discussed in Telegram and IRL.

Closing this, actual issue is [here](https://github.com/openmsupply/application-manager-web-app/issues/645)
