### ISSUE TITLE
Add re-review status to consolidation structure/progress

### ISSUE THREAD

**Issue by andreievg** [openmsupply/application-manager-web-app#712]
For normal review we have `isNewApplicationResponse`, `totalNewReviewable` and `doneNewReviewable` as per https://app.diagrams.net/#G1JmZc2daHZswUyjOFWZicJy8sttpS_-eZ

Something similar for consolidator ?

`isNewReviewResponse` -> look to see if review timestamp == review response timestamp and previous review response exists, can then calculate  `totalNewReviewable` and `doneNewReviewable`, don't include `isNewReviewResponse` in progress calculations

**Comment by nmadruga** [comment]
I just had a look on this, and I'm not sure if we need to do anything extra here... It wasn't implemented as in the description with a `isNewReviewResponse` object added to the element, but the progress on a second-review consolidation (after changes requested have been updated) is considering what is Pending to review.

This is done in this code on `helpers.tsx`:
https://github.com/openmsupply/application-manager-web-app/blob/df78130bfea234e9474cb1943ad2c458cb17880a/src/utils/hooks/useGetReviewStructureForSection/helpers.tsx#L139-L148

So, only `reviews_responses` from **lowerLevel** that are undefined (no previous answer) or that aren't linked to `review_responses` for **thisReview** will get `isPendingReview` set.  Then the new `review_responses` will be created on **start** of this second review, and the progress display correctly. Along with options to Review those. Maybe this is about displaying a option to Re-review the `review_response`?

**Comment by nmadruga** [comment]
Ok, as discussed briefly here we do want to keep an `isNewReviewResponse` in order to quickly know "How many reviews are re-review" or even display in the ui to the Consolidator what is a **new** thing to review and what was changed by lower reviewer, keeping in mind that a change from a lower level review can be either something required (`lowerLevelReviewPreviousResponse.decision` == DECLINE) or something that was not required but changed
