### ISSUE TITLE
Should hide the "Add item" on listBuilder when isEditable is false - so used for visualisation only

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#773]

**Comment by CarlosNZ** [comment]
I think it should be another parameter. Because in normal application, you want the button to remain visible (but disabled) when `isEditable = true`, otherwise there's no other (obvious) indication that it's become uneditable.

Could just add another parameter, which would default like so:
```
const {
    ... <existing parameters>
   displayOnly = false
  } = parameters
const { isEditable = displayOnly } = element
```
(So you'd only ever need to specify one of `displayOnly`/`isEditable`, never both.)

**Comment by CarlosNZ** [comment]
Functionality included with latest changes (we just show plugin as SummaryView in application), so PR for this no longer required. Closing both.
