### ISSUE TITLE
Bug: Show correct stage label on a previous stage review with - current one is showing

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#850]

**Comment by CarlosNZ** [comment]
Doing this as part of #1084 now.

**Comment by CarlosNZ** [comment]
> Doing this as part of #1084 now.

Okay, this is proving a bit trickier than anticipated, will need to leave it for its own issue I think.

**Intended solution:**

Run "refetchQueries" on 'getApplication' as part of the "submitReview" mutation, which will force the structure (and therefore stage info) to reload

**The problem:**

Problem is the trigger on the application table is never changed, so the data fetched as part of refetchQueries still contains the previous stage value. The "submit review" mutation sets the trigger on the REVIEW table, but not the APPLICATION table, so the refetch query won't wait till the trigger is reset (since it never gets set in the first place)

I then thought that it should be possible to ALSO set the trigger on the application table as part of the review submission. However, that's not possible either, as the reviewers don't have permission to write to the application table, so that doesn't work either. (It works when permissions is disabled)

Open to suggestions?

**Comment by jagoje** [comment]
@CarlosNZ Hmmm complex one - thinking about this now. I have some thoughts, will be good to chat on our meeting on Friday.

**Comment by CarlosNZ** [comment]
Apologies, I was commenting on the wrong issue. Have deleted my comments and started a new issue.
