### ISSUE TITLE
Element plugin: Text Information - missing SummaryView

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#88]

**Comment by nmadruga** [comment]
@andreievg @CarlosNZ 

Should we add the option of using dynamic labels (using the Query syntax on this property) as part of this issue?

**Comment by CarlosNZ** [comment]
> @andreievg @CarlosNZ
> 
> Should we add the option of using dynamic labels (using the Query syntax on this property) as part of this issue?

If we did it the way I was thinking it would work, then no. In my view, the "label" field (or any field) of the plugin should receive all these values pre-evaluated. But that's still up for discussion.

**Comment by andreievg** [comment]
Should also show in summary/review pages

**Comment by CarlosNZ** [comment]
I have a more general question relating to this that it'd be good to get some agreement on before addressing this issue:

It seems to me we’re not being entirely consistent with how we handle the non-question "INFORMATION" elements. I think there’s two basic approaches, and we should probably pick one and stick to it:

1. Always keep them in: responses get made for them, copies are made during review, reviewers are assigned to them, etc., so they exist in the same way as genuine “question” responses. And then we just filter them out in the UI as appropriate.
2. Get rid of them right at the start (i.e. don’t make application_responses for them at all), then we never have to deal with them thereafter.

I think I’m leaning towards (1) as I think there are situations where we need them (i.e. Summary View), and it makes keeping tracking of whether applications are "fully assigned" or not simpler (doesn't it?) but would be good to get some clarity around it since I think we’re starting to get a little slippery with how we handle them.

**Comment by andreievg** [comment]
As per our telegram discussion:

Andrei
```
Just want to point out a difference:

assignments -> get all template elements 

review -> only review application responses that are assigned with assignments (through template elements)

consolidation -> mainly cares about review responses, but when figuring out if can fully approve takes into account application responses

thus, since information template element won't have application response. it should be oki
```

Carl
```
Right, so if there’s no application_responses created for Information elements, then we’re doing Option 2 -- get rid of them early. It looks like that’s what’s happening currently. So we’re all good?
```
So far, option 2 makes the most sense, but want to make sure we dont' miss anything, below:

> I think there are situations where we need them (i.e. Summary View) 

Can we just have the same presentation for summary view as application view (it doesn't need application response)

> And it makes keeping tracking of whether applications are "fully assigned" or not simpler (doesn't it?)

Yep, I think that works with both options (as it relies on template_elements).

If we ended up going with by question assignment in UI, we would need to make sure we filter out information types from 'is_fully_assinged' column in application list view (but that should be relatively simple)
