### ISSUE TITLE
Search element showing as if updated on Changes Required

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#947]
After the applicant receives changes required (in other elements), if I click on a page with a Search element it is showing as if it had been changed by the applicant. This needs a fix:
![photo_2021-09-02_10-04-24](https://user-images.githubusercontent.com/16461988/131751644-2d165706-9f07-49a3-aa22-85054943bdce.jpg)

Tested: used `demo_2021_08_27` snapshot on Product Registration template

**Comment by CarlosNZ** [comment]
I think this is because the "text" field has changed, even though the actual selection has not. Seems like the "text" generator (it's just JSON.stringify) is putting the object fields into a different order in the output JSON string. (I think this is because the object is stored as JSON in the database, which orders the fields alphabetically, so on next load, that will become the new "text" field, rather than the original field)

Quick fix would be to update the "text" creating method to alphabetize the field order first -- this field is intended as crude placeholder, since the "text" field for this plugin should never actually be shown to users.
