### ISSUE TITLE
Use user's selected language (Log-in page)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#971]
Should also have a default language for non-registered users to show in UI 
The languages options should also be available in another area of the App maybe

When user is registering what is selected as their language should be included in the user's entity created after email confirmation. If not saved it will be using the default langague for the sytem - which is the English .js file (To be done in #970)

**Comment by CarlosNZ** [comment]
One additional complexity: since we don't have language strings for templates, only different versions, we'll need a way to specify which "User Registration" (and reset password) template to go to for creating an account. It would look super weird if you selected a language for the login screen, and then were directed to an English language form.

So perhaps the templateCode for the relevant UserReg template needs to be one of the localised strings, then we just replace it in the push request, which currently has a hard-coded user reg code.

**Comment by nmadruga** [comment]
Oh, very good point!

I wonder if it wouldn't be best and simpler to just start adding the localisation strings to the templates as well? Ahh, thinking it will be such a big task. Maybe not a good idea. Yes, I agree with that idea to add the UserRego as one of the localised strings. Good idea!

**Comment by CarlosNZ** [comment]
> I wonder if it wouldn't be best and simpler to just start adding the localisation strings to the templates as well? Ahh, thinking it will be such a big task. Maybe not a good idea.

Yeah, I think that will be too hard for now, since the templateBuilder would need a big refactor to make it work.

Should definitely start thinking about a mechanism for how it might work though, and throw some ideas around.
